version: "3"
services:
  mysql:
    container_name: test_db
    image: mysql:8
    volumes:
      - ./docker/mysql/mysqld_charset.cnf:/etc/mysql/conf.d/my.cnf
      # - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3309:3309"
    expose:
      - 3309
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: testdb
      MYSQL_TCP_PORT: 3309